[phases.setup]
nixPkgs = ["...", "playwright-driver"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "PLAYWRIGHT_BROWSERS_PATH=/opt/playwright python -m playwright install --with-deps chromium"
]

[variables]
PYTHONUNBUFFERED = "1"
PLAYWRIGHT_BROWSERS_PATH = "/opt/playwright"

[start]
cmd = "python main.py"
